name: leetcode-submit
description: Submit LeetCode solutions from CI using a session token and metadata
author: Romeo Sarkar

runs:
    using: node24
    main: dist/index.js

inputs:
    manifest-file:
        description: Path to the manifest file containing problem IDs and their corresponding solution file paths
        default: .lcsubmit.json
    leetcode-session-cookie:
        description: LEETCODE_SESSION cookie
        required: true
