on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    format_check:
        uses: ./.github/workflows/format-check.yml

    type_check:
        uses: ./.github/workflows/type-check.yml
        needs: format_check

    lint:
        uses: ./.github/workflows/lint.yml
        needs: type_check

    release_artifact_alpha:
        uses: ./.github/workflows/release-artifact-alpha.yml
        needs: lint
        permissions:
            contents: write
