on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    format_check:
        uses: ./.github/workflows/format_check.yml

    type_check:
        uses: ./.github/workflows/type_check.yml
        needs: format_check

    lint:
        uses: ./.github/workflows/lint.yml
        needs: type_check

    release_artifact:
        uses: ./.github/workflows/release-artifact.yml
        needs: lint
