name: Lint

on:
    workflow_call:

jobs:
    lint:
        runs-on: [ubuntu-latest]
        name: Lint
        steps:
            - uses: actions/checkout@v7
              name: Checkout repository

            - uses: oven-sh/setup-bun@v2
              name: Setup bun

            - run: bun install
              name: Install dependencies

            - run: bun run lint
              name: Lint
