name: Release artifact

on:
    workflow_call:

jobs:
    release_artifact:
        runs-on: [ubuntu-latest]
        name: Release artifact
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v7
              name: Checkout repository

            - uses: oven-sh/setup-bun@v2
              name: Setup bun

            - run: bun install
              name: Install dependencies

            - run: bun run build
              name: Build

            - name: Rename index.js to index.new.js
              run: mv index.js index.new.js

            - name: Fetch all branches
              run: git fetch --all

            - name: List all branches
              run: git --no-pager branch -a

            - name: Create / checkout relase branch
              run: |
                  if git ls-remote --exit-code --heads origin release; then
                      git checkout -b release origin/release
                  else
                      echo Creating orphan branch...

                      git checkout --orphan release
                      git rm -rf .

                      echo '*' > .gitignore
                      echo '!/.gitignore' >> .gitignore
                      echo '!/index.js' >> .gitignore
                      echo '!/action.yml' >> .gitignore
                  fi

            - name: Checkout action.yml from origin/main
              run: git restore --source origin/main action.yml

            - name: Rename new.index.js back to index.js
              run: mv index.new.js index.js

            - name: Commit changes
              run: |
                  if ! git diff --quiet HEAD || [ -n "$(git ls-files --others --exclude-standard)" ] ; then
                      git stage .
                      git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m 'Automated release for commit $(git rev-parse origin/main)'
                  else
                      echo 'Nothing to commit!'
                  fi

            - name: Push release
              run: git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} release
